// Generated by Melange
'use strict';


function encode(prim) {
  return btoa(prim);
}

function decode(prim) {
  return atob(prim);
}

exports.encode = encode;
exports.decode = decode;
/* No side effect */
