// Generated by Melange
'use strict';

var Css = require("bs-css-emotion/./src/Css.bs.js");
var Curry = require("melange/lib/js/curry.js");
var React = require("react");
var Marked = require("marked");
var Relude_IO = require("relude/./src/Relude_IO.bs.js");
var Dompurify = require("dompurify");
var ReactDom = require("react-dom");
var ReludeFetch = require("relude-fetch/./src/ReludeFetch.bs.js");
var Relude_Result = require("relude/./src/Relude_Result.bs.js");
var Relude_Globals = require("relude/./src/Relude_Globals.bs.js");
var Decode_ParseError = require("bs-decode/./src/Decode_ParseError.bs.js");
var ReludeFetch_Error = require("relude-fetch/./src/ReludeFetch_Error.bs.js");
var GithubApi$Tritesite = require("./GithubApi.bs.js");
var ReludeFetch_Response = require("relude-fetch/./src/ReludeFetch_Response.bs.js");

var contentRoot = "https://api.github.com/repos/trite/trite.io-content/contents/";

function makeUri(path) {
  return contentRoot + path;
}

function show(error) {
  return ReludeFetch_Error.show((function (a) {
                return a;
              }), error);
}

var Type = {};

var $$Error = {
  show: show,
  Type: Type
};

var IOE = Relude_IO.WithError(Type);

function fetchString(uri) {
  return Curry._2(IOE.Infix.$great$great$eq, ReludeFetch.$$fetch(uri), ReludeFetch_Response.text);
}

var ContentFetch = {
  $$Error: $$Error,
  IOE: IOE,
  fetchString: fetchString
};

function Sandbox$S(Props) {
  return Props.children;
}

var S = {
  make: Sandbox$S
};

var wideTextInput = Curry._1(Css.style, {
      hd: Css.width(Css.pct(50.0)),
      tl: /* [] */0
    });

var wideTextArea = Curry._1(Css.style, {
      hd: Css.width(Css.pct(50.0)),
      tl: {
        hd: Css.height(Css.px(150)),
        tl: /* [] */0
      }
    });

var Styles = {
  wideTextInput: wideTextInput,
  wideTextArea: wideTextArea
};

function getValue(e) {
  return e.target.value;
}

function parseAndSet(setter, $$event) {
  var x = Dompurify.sanitize(Marked.parse($$event.target.value));
  return Curry._1(setter, (function (param) {
                return x;
              }));
}

function foldUnitResults(param) {
  return Relude_Result.fold((function (param) {
                
              }), (function (param) {
                
              }), param);
}

function $$fetch(setter, uri, _event) {
  Relude_IO.unsafeRunAsync(foldUnitResults, Curry._2(Relude_IO.mapError, (function (error) {
              Curry._1(setter, (function (param) {
                      return ReludeFetch_Error.show((function (a) {
                                    return a;
                                  }), error);
                    }));
            }), Relude_IO.map((function (content) {
                  Curry._1(setter, (function (param) {
                          return content;
                        }));
                }), fetchString(uri))));
}

function doSpecificFetch(specificFetch, setSpecificFetchResult, _event) {
  Relude_IO.unsafeRunAsync(foldUnitResults, Curry._2(Relude_IO.mapError, (function (error) {
              Curry._1(setSpecificFetchResult, (function (param) {
                      return ReludeFetch_Error.show((function (a) {
                                    return a;
                                  }), error);
                    }));
            }), Relude_IO.map((function (param) {
                  return Relude_Globals.$great$great((function (param) {
                                return Relude_Globals.$great$great((function (prim) {
                                              return JSON.parse(prim);
                                            }), GithubApi$Tritesite.decodeTest, param);
                              }), (function (param) {
                                return Relude_Result.fold((function (err) {
                                              Curry._1(setSpecificFetchResult, (function (param) {
                                                      return Decode_ParseError.failureToDebugString(err);
                                                    }));
                                            }), (function (param) {
                                              return Relude_Globals.$great$great(GithubApi$Tritesite.githubApiResponseToString, (function (x) {
                                                            Curry._1(setSpecificFetchResult, (function (param) {
                                                                    return x;
                                                                  }));
                                                          }), param);
                                            }), param);
                              }), param);
                }), fetchString(contentRoot + specificFetch))));
}

function Sandbox$App(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setParsedMarkdown = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setFetched = match$1[1];
  var match$2 = React.useState(function () {
        return "posts/2022/2022-01-18_python-type-checking.md";
      });
  var setSpecificFetch = match$2[1];
  var specificFetch = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setSpecificFetchResult = match$3[1];
  var match$4 = React.useState(function () {
        return "";
      });
  var setAscii = match$4[1];
  var ascii = match$4[0];
  var match$5 = React.useState(function () {
        return "";
      });
  var setBase64 = match$5[1];
  var base64 = match$5[0];
  return React.createElement("div", undefined, React.createElement("label", undefined, React.createElement(Sandbox$S, {
                      children: "Markdown parse test: "
                    })), React.createElement("textarea", {
                  className: wideTextArea,
                  onChange: (function (param) {
                      return parseAndSet(setParsedMarkdown, param);
                    })
                }), React.createElement("br", undefined), React.createElement("div", {
                  dangerouslySetInnerHTML: {
                    __html: match[0]
                  }
                }), React.createElement("br", undefined), React.createElement("hr", undefined), React.createElement("br", undefined), React.createElement("label", undefined, React.createElement(Sandbox$S, {
                      children: "Specific fetch test: "
                    })), React.createElement("input", {
                  className: wideTextInput,
                  type: "text",
                  value: specificFetch,
                  onChange: (function (param) {
                      return Relude_Globals.$great$great(getValue, setSpecificFetch, param);
                    })
                }), React.createElement("input", {
                  type: "button",
                  value: "go forth and fetch the thing",
                  onClick: (function (param) {
                      return doSpecificFetch(specificFetch, setSpecificFetchResult, param);
                    })
                }), React.createElement("br", undefined), React.createElement("pre", undefined, React.createElement(Sandbox$S, {
                      children: match$3[0]
                    })), React.createElement("br", undefined), React.createElement("hr", undefined), React.createElement("br", undefined), React.createElement("label", undefined, React.createElement(Sandbox$S, {
                      children: "Fetch test: "
                    })), React.createElement("span", {
                  value: match$1[0]
                }), React.createElement("input", {
                  type: "button",
                  value: "dooo it",
                  onClick: (function (param) {
                      return $$fetch(setFetched, contentRoot, param);
                    })
                }), React.createElement("br", undefined), React.createElement("hr", undefined), React.createElement("br", undefined), React.createElement("textarea", {
                  className: wideTextArea,
                  value: ascii,
                  onChange: (function (param) {
                      return Relude_Globals.$great$great(getValue, setAscii, param);
                    })
                }), React.createElement("br", undefined), React.createElement("input", {
                  type: "button",
                  value: "ascii -> base64",
                  onClick: (function (param) {
                      var x = atob(ascii);
                      Curry._1(setBase64, (function (param) {
                              return x;
                            }));
                    })
                }), React.createElement("input", {
                  type: "button",
                  value: "ascii <- base64",
                  onClick: (function (param) {
                      var x = btoa(base64);
                      Curry._1(setAscii, (function (param) {
                              return x;
                            }));
                    })
                }), React.createElement("br", undefined), React.createElement("textarea", {
                  className: wideTextArea,
                  value: base64,
                  onChange: (function (param) {
                      return Relude_Globals.$great$great(getValue, setBase64, param);
                    })
                }));
}

var App = {
  getValue: getValue,
  parseAndSet: parseAndSet,
  foldUnitResults: foldUnitResults,
  $$fetch: $$fetch,
  doSpecificFetch: doSpecificFetch,
  make: Sandbox$App
};

var root = document.querySelector("#root");

if (root == null) {
  console.error("Failed to start React: couldn't find the #root element");
} else {
  ReactDom.render(React.createElement(Sandbox$App, {}), root);
}

exports.contentRoot = contentRoot;
exports.makeUri = makeUri;
exports.ContentFetch = ContentFetch;
exports.S = S;
exports.Styles = Styles;
exports.App = App;
/* IOE Not a pure module */
